config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:create, :new, :show]
  resource :session, only:[:create, :new, :destroy]
  resources :bands do
    resources :albums, only:[:new]
  end

  resources :albums, except:[:new, :index] do
    resources :tracks, only:[:new]
  end

  resources :tracks, except:[:new, :index]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, :live, presence:true
  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  dependent: :destroy,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: :Track
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence:true
  has_many :albums,
  dependent: :destroy,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album

  has_many :tracks,
  through: :albums,
  source: :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :bonus, presence:true

  belongs_to :album,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: :Album
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: {message: "Must be 6 chars"}
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token

  attr_reader :password

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  # def is_password?(pw)
  #   self.password_digest == BCrypt::Password.create(pw)
  # end

  def self.find_by_credentials(email, pw)
    user = User.find_by(email: email)
    return user if user && BCrypt::Password.new(user.password_digest).is_password?(pw)
    nil
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!
  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout!
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url unless current_user
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!
  def index
    @bands = Band.all
    render :index
  end


  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render text: "fuku"
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = Band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!
  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to bands_url
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :bonus, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :session_token, :password)
  end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Album</title>
</head>
<body>
<h1>Edit Album</h1>
 <form action="<%= album_url(@album) %>" method="post">
   <input type="hidden" name="_method" value="patch">
   <%= auth_token %>
     <label for="album_name"> Name </label>
     <input type="text"
     name="album[name]"
     id="album_name"
     value="<%=@album.name%>">
  <br>



  <input type ="radio"
  name="album[live]"
  id="album_live"
  value="Live"
  <%= @album.live == "Live" ? "checked" : ""%>>
  <label for="album_live"> Live</label>
  <input type ="radio"
  name="album[live]"
  id="album_live"
  value="Studio"
  <%= @album.live == "Studio" ? "checked" : ""%>>
  <label for="album_live"> Studio</label>
<br>
  <label for="album_band_id"> Band </label>
  <select name="album[band_id]" id="album_band_id">
    <%= Band.all.each do |band| %>
      <option <%= @album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>"> <%=band.name%>
      </option>
      <%end%>
    </select>
  <input type="submit">
 </form>

</body>
</html>

app/views/albums/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Album</title>
</head>
<body>
<h1>New Album</h1>
 <form action="<%= albums_url %>" method="post">
   <%= auth_token %>
     <label for="album_name"> Name </label>
     <input type="text"
     name="album[name]"
     id="album_name">
  <br>


  <input type ="radio"
  name="album[live]"
  id="album_live"
  value="Live"
  checked>
  <label for="album_live"> Live</label>
  <input type ="radio"
  name="album[live]"
  id="album_live"
  value="Studio"
  checked>
  <label for="album_live"> Studio</label>
<br>
  <label for="album_band_id"> Band </label>
  <select name="album[band_id]" id="album_band_id">
    <%= Band.all.each do |band| %>
      <option <%= @album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>"> <%=band.name%>
      </option>
      <%end%>
    </select>
  <input type="submit">
 </form>

</body>
</html>

app/views/albums/show.html.erb
<br>
<%= "#{@album.name} by #{@album.band.name}" %>
<br>
<%= button_to "edit album", edit_album_url, method: :get %>
<br>
<%= button_to "delete album", album_url(@album), method: :delete %>
<br>


<% @album.tracks.each do |track| %>
  <a href="<%=track_url(track)%>"> <%= "#{track.name}, #{track.bonus}" %></a>
  <br>
  <%= button_to "edit track", edit_track_url, method: :get %>
  <%= button_to "delete track", track_url(track), method: :delete%>
  <br>
<% end %>
<br>
<%= button_to "add track", new_album_track_url(@album), method: :get %>
<br>
<%= link_to "artist", band_url(@album.band), method: :get %>

app/views/bands/edit.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Edit Band</title>
</head>
<body>
<h1>New Band Name</h1>
<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
    <label for="band_name"> Name </label>
    <input type="text"
    name="band[name]"
    id="band_name"
    value="<%=@band.name%>">
 <br>

 <input type="submit">
</form>

</body>
</html>

app/views/bands/index.html.erb
<h1>Bands Index</h1>
  <a href="<%= new_band_url %>">  Add Band  </a>
  <br>
    <% @bands.each do |band| %>
      <a href="<%=band_url(band)%>"> <%= band.name %></a>
      <br>
      <%= button_to "Delet this", band_url(band), method: :delete%>
      <br>
    <% end %>

app/views/bands/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Band</title>
</head>
<body>
<h1>New Band Name</h1>
 <form action="<%= bands_url %>" method="post">
   <%= auth_token %>
     <label for="band_name"> Name </label>
     <input type="text"
     name="band[name]"
     id="band_name">
  <br>

  <input type="submit">
 </form>

</body>
</html>

app/views/bands/show.html.erb
<br>
<%= @band.name %>
<br>
<%= button_to "edit band name", edit_band_url, method: :get %>
<br>
<%= button_to "delete band", band_url(@band), method: :delete %>
<br>


<% @band.albums.each do |album| %>
  <a href="<%=album_url(album)%>"> <%= "#{album.name}, #{album.live}" %></a>
  <br>
  <%= button_to "edit album", edit_album_url, method: :get %>
  <%= button_to "delete album", album_url(album), method: :delete%>
  <br>
<% end %>
<br>
<%= button_to "add album", new_band_album_url(@band), method: :get %>
<br>
<%= link_to "bands index", bands_url, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  <%= button_to "Log out", session_url, method: :delete %>
  <% else %>
  <%= link_to "Log In", new_session_url %>
  <%= link_to "Register", new_user_url %>
  <% end %>


<%= yield %>

</body>
</html>

app/views/tracks/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Track</title>
</head>
<body>
<h1>Edit Track</h1>

 <form action="<%= track_url(@track) %>" method="post">
   <input type="hidden" name="_method" value="patch">
   <%= auth_token %>


     <label for="track_name"> Name </label>
     <input type="text"
     name="track[name]"
     id="track_name"
     value="<%=@track.name%>">
  <br>

  <label for="album_band_id"> Band </label>
  <select name="track[album_id]" id="track_album_id">
    <%= Album.all.each do |album| %>
      <option <%= @track.album_id == album.id ? "selected" : "" %>
        value="<%= album.id %>"> <%=album.name%>
      </option>
      <%end%>
    </select>
    <br>


  <input type ="radio"
  name="track[bonus]"
  id="track_bonus"
  value="Bonus"
  <%= @track.bonus == "Bonus" ? "checked" : ""%>>
  <label for="track_bonus"> Bonus</label>

  <input type ="radio"
  name="track[bonus]"
  id="track_bonus"
  value="Regular"
  <%= @track.bonus == "Regular" ? "checked" : ""%>>
  <label for="track_bonus"> Regular</label>
<br>


<label>
  Lyrics
  <br>
  <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
</label>
<br>


  <input type="submit">
 </form>
<br>
</body>
</html>

app/views/tracks/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Track</title>
</head>
<body>
<h1>New Track</h1>

 <form action="<%= tracks_url %>" method="post">
   <%= auth_token %>


     <label for="track_name"> Name </label>
     <input type="text"
     name="track[name]"
     id="track_name">
  <br>

  <label for="album_band_id"> Band </label>
  <select name="track[album_id]" id="track_album_id">
    <%= Album.all.each do |album| %>
      <option <%= @track.album_id == album.id ? "selected" : "" %>
        value="<%= album.id %>"> <%=album.name%>
      </option>
      <%end%>
    </select>
    <br>


  <input type ="radio"
  name="track[bonus]"
  id="track_bonus"
  value="Bonus"
  checked>
  <label for="track_bonus"> Bonus</label>

  <input type ="radio"
  name="track[bonus]"
  id="track_bonus"
  value="Regular"
  checked>
  <label for="track_bonus"> Regular</label>
<br>


<label>
  Lyrics
  <br>
  <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
</label>
<br>


  <input type="submit">
 </form>
<br>
</body>
</html>

app/views/tracks/show.html.erb
<br>
<%= "#{@track.name} from #{@track.album.name}" %>
<br>
<%= button_to "edit track", edit_track_url, method: :get %>
<br>
<%= button_to "delete track", track_url(@track), method: :delete %>
<br>

<%= "#{@track.lyrics}" %>


<%= link_to "album", album_url(@track.album), method: :get %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New User</title>
</head>
<body>
<h1>Sign up</h1>
 <form action="<%= users_url %>" method="post">
   <%= auth_token %>
     <label for="user_email"> Email </label>
     <input type="text"
     name="user[email]"
     id="user_email"
     value="<%=@user.email%>">
   <br>

   <label for="user_password"> Password </label>
     <input type="password"
     name="user[password]"
     id="user_password"
     value="<%=@user.password%>">
   <br>
         <input type="submit">
 </form>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Profile</title>
</head>
<body>
  <%= @user.email %>

</body>
</html>